// ───── Listings seed data (merged with extras) ─────

export const SEED_LISTINGS = [
  {
    id: 1,
    name: '太古城中心豪裝兩房',
    categories: ['all', 'estate'],
    location: '太古城，東區',
    mapLocation: '太古城',
    latitude: 22.2839,
    longitude: 114.216,
    badge: '業主直租',
    subtitle: '私人屋苑 · 2房1廁 · 即租',
    availableDates: '即時入住',
    listedDate: '2025-09-10',
    updatedDate: '2025-10-15',
    price: 22000,
    rating: 4.9,
    reviews: 34,
    photos: [] as string[],
    area: 720,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: '私人屋苑',
    leaseTerm: '12個月',
    description:
      '太古城中心高層單位，座向開揚，室內裝修簇新，廚房及浴室均經翻新。步行5分鐘到太古地鐵站，商場、超市、餐廳一應俱全。業主誠意放租，歡迎預約睇樓。',
    features: [
      '業主直租 — 免佣金，直接與業主聯絡',
      '全新裝修 — 廚房及浴室均於2024年翻新',
      '交通便利 — 步行5分鐘到太古地鐵站',
    ],
    amenities: ['elevator', 'security', 'gym'],
  },
  {
    id: 2,
    name: '西貢海景村屋連車位',
    categories: ['all', 'village'],
    location: '西貢，新界東',
    mapLocation: '西貢',
    latitude: 22.3823,
    longitude: 114.2707,
    badge: '',
    subtitle: '村屋 · 3房2廁 · 連車位',
    availableDates: '2025年4月1日起',
    listedDate: '2025-02-20',
    updatedDate: '2025-10-01',
    price: 28000,
    rating: 4.8,
    reviews: 19,
    photos: [] as string[],
    area: 1800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: '村屋',
    leaseTerm: '12個月',
    description:
      '西貢三層村屋，連私人花園及車位，環境清幽，海風習習。頂層設開放式天台，可遠眺西貢海景。適合喜愛郊外生活的家庭，附近有超市、街市及多間特色海鮮餐廳。',
    features: [
      '連私人車位 — 車位已包含於租金內',
      '三層村屋 — 每層獨立起居空間',
      '近西貢市中心 — 駕車約5分鐘',
    ],
    amenities: ['parking', 'balcony', 'pets'],
  },
  {
    id: 3,
    name: '山頂獨立洋房全海景',
    categories: ['all', 'luxury'],
    location: '山頂，中西區',
    mapLocation: '山頂',
    latitude: 22.2718,
    longitude: 114.1452,
    badge: '新上架',
    subtitle: '豪宅 · 4房3廁 · 私人泳池',
    availableDates: '2025年5月1日起',
    listedDate: '2025-10-05',
    updatedDate: '2025-10-20',
    price: 85000,
    rating: 5.0,
    reviews: 8,
    photos: [] as string[],
    area: 3200,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: '豪宅',
    leaseTerm: '24個月',
    description:
      '山頂稀有獨立洋房，坐擁360度全海景，室內設私人泳池、健身室及娛樂室。高端智能家居系統，進口廚具，管家服務可按需安排。極罕見盤源，適合追求頂級生活品味之人士。',
    features: [
      '私人泳池 — 室內恆溫泳池',
      '全景視野 — 維港、南丫島一覽無遺',
      '豪華裝修 — 意大利進口大理石地台',
    ],
    amenities: ['pool', 'gym', 'security', 'parking', 'balcony'],
  },
  {
    id: 4,
    name: '旺角唐樓開放式裝修靚',
    categories: ['all', 'tong'],
    location: '旺角，油尖旺',
    mapLocation: '旺角',
    latitude: 22.3193,
    longitude: 114.1694,
    badge: '業主直租',
    subtitle: '唐樓 · 開放式 · 近地鐵',
    availableDates: '即時入住',
    listedDate: '2025-08-01',
    updatedDate: '2025-10-12',
    price: 8500,
    rating: 4.7,
    reviews: 52,
    photos: [] as string[],
    area: 280,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: '唐樓',
    leaseTerm: '12個月',
    description:
      '旺角鬧市中心唐樓開放式單位，裝修整潔，傢俬電器齊備，即租即住。步行1分鐘到旺角地鐵站，生活配套極方便。適合單身人士或學生。',
    features: [
      '即租即住 — 傢俬電器全包',
      '地鐵一分鐘 — 旺角站A出口',
      '生活便利 — 樓下便利店及茶餐廳',
    ],
    amenities: ['elevator'],
  },
  {
    id: 5,
    name: '日出康城1房精裝修',
    categories: ['all', 'estate'],
    location: '將軍澳，西貢區',
    mapLocation: '將軍澳',
    latitude: 22.3072,
    longitude: 114.2597,
    badge: '業主直租',
    subtitle: '私人屋苑 · 1房1廁 · 海景',
    availableDates: '即時入住',
    listedDate: '2025-09-18',
    updatedDate: '2025-10-18',
    price: 14500,
    rating: 4.8,
    reviews: 27,
    photos: [] as string[],
    area: 430,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: '私人屋苑',
    leaseTerm: '12個月',
    description:
      '日出康城Phase 1一房一廳，高層海景，裝修時尚，廚房採開放式設計。屋苑設會所、泳池、健身室等豐富設施，鄰近將軍澳地鐵站，交通方便。',
    features: [
      '高層海景 — 清水灣海景無遮擋',
      '會所設施 — 泳池、健身室、兒童遊樂場',
      '近地鐵站 — 步行8分鐘到將軍澳站',
    ],
    amenities: ['elevator', 'pool', 'gym', 'security'],
  },
  {
    id: 6,
    name: '半山豪宅三房全維港景',
    categories: ['all', 'luxury'],
    location: '半山，中西區',
    mapLocation: '半山',
    latitude: 22.28,
    longitude: 114.153,
    badge: '',
    subtitle: '豪宅 · 3房2廁 · 維港全景',
    availableDates: '2025年4月15日起',
    listedDate: '2025-10-05',
    updatedDate: '2025-10-19',
    price: 62000,
    rating: 4.9,
    reviews: 15,
    photos: [] as string[],
    area: 1650,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: '豪宅',
    leaseTerm: '24個月',
    description:
      '半山高層三房大宅，維港全景一覽無遺，裝修豪華，主人套房設步入式衣帽間及浴缸。24小時保安及禮賓服務，名校網覆蓋，適合外籍家庭入住。',
    features: [
      '維港全景 — 270°開揚景觀',
      '頂級裝修 — 意大利廚具，智能系統',
      '名校網 — 近多間國際學校',
    ],
    amenities: ['elevator', 'security', 'gym', 'parking'],
  },
  {
    id: 7,
    name: '沙田第一城兩房實用靚則',
    categories: ['all', 'estate'],
    location: '沙田，新界',
    mapLocation: '沙田',
    latitude: 22.3797,
    longitude: 114.1878,
    badge: '',
    subtitle: '私人屋苑 · 2房1廁 · 近火車站',
    availableDates: '即時入住',
    listedDate: '2025-07-22',
    updatedDate: '2025-09-29',
    price: 16800,
    rating: 4.7,
    reviews: 41,
    photos: [] as string[],
    area: 580,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: '私人屋苑',
    leaseTerm: '12個月',
    description:
      '沙田第一城中層兩房，實用靚則，採光充足，窗外對翠綠山景。屋苑管理完善，會所設施齊全，鄰近沙田火車站及新城市廣場，生活配套極佳。',
    features: [
      '實用靚則 — 方正格局，空間感強',
      '山景單位 — 對翠綠山景，環境清幽',
      '近火車站 — 步行5分鐘到沙田站',
    ],
    amenities: ['elevator', 'security', 'gym', 'pool'],
  },
  {
    id: 8,
    name: '大埔獨立屋連花園車位',
    categories: ['all', 'house'],
    location: '大埔，新界',
    mapLocation: '大埔',
    latitude: 22.4452,
    longitude: 114.1644,
    badge: '業主直租',
    subtitle: '獨立屋 · 4房2廁 · 連花園',
    availableDates: '2025年5月15日起',
    listedDate: '2025-10-10',
    updatedDate: '2025-10-22',
    price: 38000,
    rating: 4.9,
    reviews: 22,
    photos: [] as string[],
    area: 2400,
    bedrooms: 4,
    bathrooms: 2,
    propertyType: '獨立屋',
    leaseTerm: '24個月',
    description:
      '大埔三層獨立屋，連私人花園及車位，環境清幽，附近有大埔墟街市及大型超市。距大埔墟火車站約10分鐘步行，適合喜愛新界生活的大家庭。',
    features: [
      '私人花園 — 約400呎花園，可舉辦戶外活動',
      '四房大宅 — 適合三代同堂家庭',
      '連車位 — 可停泊兩部私家車',
    ],
    amenities: ['parking', 'balcony', 'pets'],
  },
];

// ───── Categories seed data ─────

export const SEED_CATEGORIES = [
  {
    key: 'all',
    label: '所有物業',
    icon: '<path d="M16 2L2 14h4v16h8v-8h4v8h8V14h4z" fill="currentColor" opacity=".8"/>',
  },
  {
    key: 'estate',
    label: '私人屋苑',
    icon: '<rect x="4" y="6" width="24" height="22" rx="2" stroke="currentColor" stroke-width="2" fill="none"/><rect x="9" y="11" width="4" height="4" rx="1" fill="currentColor"/><rect x="19" y="11" width="4" height="4" rx="1" fill="currentColor"/><rect x="9" y="19" width="4" height="4" rx="1" fill="currentColor"/><rect x="19" y="19" width="4" height="4" rx="1" fill="currentColor"/><path d="M13 28v-5h6v5" fill="currentColor"/>',
  },
  {
    key: 'village',
    label: '村屋',
    icon: '<path d="M4 16L16 6l12 10" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/><rect x="8" y="16" width="16" height="12" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><rect x="13" y="22" width="6" height="6" fill="currentColor" rx="1"/><path d="M3 26c0-3 3-5 3-5M29 26c0-3-3-5-3-5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" fill="none"/>',
  },
  {
    key: 'tong',
    label: '唐樓',
    icon: '<rect x="6" y="4" width="20" height="24" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><rect x="10" y="8" width="4" height="3" rx="0.5" fill="currentColor"/><rect x="18" y="8" width="4" height="3" rx="0.5" fill="currentColor"/><rect x="10" y="15" width="4" height="3" rx="0.5" fill="currentColor"/><rect x="18" y="15" width="4" height="3" rx="0.5" fill="currentColor"/><rect x="12" y="22" width="8" height="6" rx="0.5" fill="currentColor"/>',
  },
  {
    key: 'commercial',
    label: '工商廈',
    icon: '<rect x="8" y="2" width="16" height="26" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><rect x="2" y="10" width="6" height="18" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><rect x="24" y="10" width="6" height="18" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><rect x="12" y="6" width="3" height="3" fill="currentColor"/><rect x="17" y="6" width="3" height="3" fill="currentColor"/><rect x="12" y="13" width="3" height="3" fill="currentColor"/><rect x="17" y="13" width="3" height="3" fill="currentColor"/>',
  },
  {
    key: 'luxury',
    label: '豪宅',
    icon: '<polygon points="16,4 20,13 30,13 22,19 25,29 16,23 7,29 10,19 2,13 12,13" stroke="currentColor" stroke-width="2" fill="none"/>',
  },
  {
    key: 'house',
    label: '獨立屋',
    icon: '<path d="M2 14L16 3l14 11" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/><rect x="5" y="14" width="22" height="15" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><rect x="12" y="20" width="8" height="9" rx="1" fill="currentColor"/><path d="M2 14h28" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
  },
  {
    key: 'parking',
    label: '車位',
    icon: '<rect x="3" y="6" width="26" height="20" rx="2" stroke="currentColor" stroke-width="2" fill="none"/><path d="M10 22V10h7a4 4 0 010 8h-7" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>',
  },
  {
    key: 'shop',
    label: '工商舖',
    icon: '<rect x="2" y="12" width="28" height="16" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><path d="M2 12l4-8h20l4 8" stroke="currentColor" stroke-width="2" fill="none" stroke-linejoin="round"/><rect x="11" y="18" width="10" height="10" rx="1" fill="currentColor"/><path d="M2 12h28" stroke="currentColor" stroke-width="2"/>',
  },
];

// ───── School nets seed data ─────

export const SEED_SCHOOL_NETS = [
  { mapLocation: '太古城', primarySchoolNet: '第14組', secondarySchoolNet: '東區' },
  { mapLocation: '西貢', primarySchoolNet: '第95組', secondarySchoolNet: '西貢區' },
  { mapLocation: '山頂', primarySchoolNet: '第11組', secondarySchoolNet: '中西區' },
  { mapLocation: '旺角', primarySchoolNet: '第31組', secondarySchoolNet: '油尖旺區' },
  { mapLocation: '將軍澳', primarySchoolNet: '第95組', secondarySchoolNet: '西貢區' },
  { mapLocation: '半山', primarySchoolNet: '第11組', secondarySchoolNet: '中西區' },
  { mapLocation: '沙田', primarySchoolNet: '第89組', secondarySchoolNet: '沙田區' },
  { mapLocation: '大埔', primarySchoolNet: '第84組', secondarySchoolNet: '大埔區' },
];

// ───── Rental transactions seed data ─────

export const SEED_RENTAL_TRANSACTIONS = [
  // 太古城 — 東區 estate
  { date: '2025-10-08', district: '太古城', building: '太古城中心', categories: ['estate'], unitType: '2房1廁', area: 720, monthlyRent: 22000 },
  { date: '2025-08-14', district: '太古城', building: '太古城中心', categories: ['estate'], unitType: '1房1廁', area: 510, monthlyRent: 16500 },
  { date: '2025-06-03', district: '太古城', building: '愛秩序灣', categories: ['estate'], unitType: '2房1廁', area: 680, monthlyRent: 20000 },
  { date: '2025-03-19', district: '太古城', building: '太古城中心', categories: ['estate'], unitType: '3房2廁', area: 980, monthlyRent: 30000 },
  { date: '2024-12-27', district: '太古城', building: '愛秩序灣', categories: ['estate'], unitType: '1房1廁', area: 490, monthlyRent: 15800 },
  { date: '2024-10-11', district: '太古城', building: '太古城中心', categories: ['estate'], unitType: '2房1廁', area: 700, monthlyRent: 21000 },
  { date: '2024-07-22', district: '太古城', building: '太古灣', categories: ['estate'], unitType: '開放式', area: 320, monthlyRent: 11500 },

  // 西貢 — village
  { date: '2025-09-25', district: '西貢', building: '西貢村屋', categories: ['village'], unitType: '3房2廁', area: 1800, monthlyRent: 28000 },
  { date: '2025-07-10', district: '西貢', building: '清水灣村屋', categories: ['village'], unitType: '3房2廁', area: 1650, monthlyRent: 26000 },
  { date: '2025-04-18', district: '西貢', building: '西貢村屋', categories: ['village'], unitType: '2房1廁', area: 1200, monthlyRent: 20000 },
  { date: '2025-01-30', district: '西貢', building: '坑口村屋', categories: ['village'], unitType: '3房2廁', area: 1700, monthlyRent: 24000 },
  { date: '2024-11-05', district: '西貢', building: '清水灣村屋', categories: ['village'], unitType: '2房1廁', area: 1100, monthlyRent: 18500 },
  { date: '2024-08-20', district: '西貢', building: '坑口村屋', categories: ['village'], unitType: '4房2廁', area: 2200, monthlyRent: 35000 },

  // 山頂 — luxury
  { date: '2025-10-01', district: '山頂', building: '天比高', categories: ['luxury'], unitType: '4房3廁', area: 3200, monthlyRent: 85000 },
  { date: '2025-07-28', district: '山頂', building: '環翠園', categories: ['luxury'], unitType: '3房2廁', area: 2400, monthlyRent: 65000 },
  { date: '2025-05-12', district: '山頂', building: '天比高', categories: ['luxury'], unitType: '4房3廁', area: 3000, monthlyRent: 80000 },
  { date: '2025-02-06', district: '山頂', building: '山頂道別墅', categories: ['luxury'], unitType: '5房4廁', area: 4500, monthlyRent: 120000 },
  { date: '2024-11-19', district: '山頂', building: '環翠園', categories: ['luxury'], unitType: '3房2廁', area: 2200, monthlyRent: 60000 },
  { date: '2024-09-03', district: '山頂', building: '天比高', categories: ['luxury'], unitType: '4房3廁', area: 3100, monthlyRent: 82000 },

  // 旺角 — tong
  { date: '2025-10-12', district: '旺角', building: '旺角唐樓', categories: ['tong'], unitType: '開放式', area: 280, monthlyRent: 8500 },
  { date: '2025-08-01', district: '旺角', building: '旺角唐樓', categories: ['tong'], unitType: '1房1廁', area: 380, monthlyRent: 11000 },
  { date: '2025-05-20', district: '旺角', building: '亞皆老街唐樓', categories: ['tong'], unitType: '開放式', area: 260, monthlyRent: 8000 },
  { date: '2025-02-14', district: '旺角', building: '洗衣街唐樓', categories: ['tong'], unitType: '1房1廁', area: 350, monthlyRent: 10500 },
  { date: '2024-12-09', district: '旺角', building: '旺角唐樓', categories: ['tong'], unitType: '2房1廁', area: 480, monthlyRent: 14000 },
  { date: '2024-09-28', district: '旺角', building: '亞皆老街唐樓', categories: ['tong'], unitType: '開放式', area: 255, monthlyRent: 7800 },

  // 將軍澳 — estate
  { date: '2025-09-18', district: '將軍澳', building: '日出康城', categories: ['estate'], unitType: '1房1廁', area: 430, monthlyRent: 14500 },
  { date: '2025-07-05', district: '將軍澳', building: '日出康城', categories: ['estate'], unitType: '2房1廁', area: 620, monthlyRent: 19000 },
  { date: '2025-04-22', district: '將軍澳', building: '新都城', categories: ['estate'], unitType: '1房1廁', area: 400, monthlyRent: 13500 },
  { date: '2025-01-08', district: '將軍澳', building: '新都城', categories: ['estate'], unitType: '2房1廁', area: 590, monthlyRent: 17500 },
  { date: '2024-10-30', district: '將軍澳', building: '日出康城', categories: ['estate'], unitType: '3房2廁', area: 820, monthlyRent: 25000 },
  { date: '2024-08-15', district: '將軍澳', building: '維景灣畔', categories: ['estate'], unitType: '1房1廁', area: 420, monthlyRent: 14000 },

  // 半山 — luxury
  { date: '2025-10-05', district: '半山', building: '干德道豪宅', categories: ['luxury'], unitType: '3房2廁', area: 1650, monthlyRent: 62000 },
  { date: '2025-08-22', district: '半山', building: '嘉富麗苑', categories: ['luxury'], unitType: '2房2廁', area: 1100, monthlyRent: 42000 },
  { date: '2025-06-09', district: '半山', building: '干德道豪宅', categories: ['luxury'], unitType: '4房3廁', area: 2200, monthlyRent: 85000 },
  { date: '2025-03-27', district: '半山', building: '嘉富麗苑', categories: ['luxury'], unitType: '3房2廁', area: 1550, monthlyRent: 58000 },
  { date: '2024-12-14', district: '半山', building: '羅便臣道大廈', categories: ['luxury'], unitType: '2房1廁', area: 980, monthlyRent: 38000 },
  { date: '2024-10-01', district: '半山', building: '干德道豪宅', categories: ['luxury'], unitType: '3房2廁', area: 1600, monthlyRent: 60000 },

  // 沙田 — estate
  { date: '2025-09-29', district: '沙田', building: '第一城', categories: ['estate'], unitType: '2房1廁', area: 580, monthlyRent: 16800 },
  { date: '2025-07-17', district: '沙田', building: '第一城', categories: ['estate'], unitType: '1房1廁', area: 410, monthlyRent: 12500 },
  { date: '2025-04-04', district: '沙田', building: '沙田第一城', categories: ['estate'], unitType: '3房2廁', area: 820, monthlyRent: 22000 },
  { date: '2025-01-21', district: '沙田', building: '廣源邨', categories: ['estate'], unitType: '2房1廁', area: 540, monthlyRent: 15000 },
  { date: '2024-11-08', district: '沙田', building: '第一城', categories: ['estate'], unitType: '2房1廁', area: 570, monthlyRent: 16000 },
  { date: '2024-08-26', district: '沙田', building: '廣源邨', categories: ['estate'], unitType: '1房1廁', area: 395, monthlyRent: 12000 },

  // 大埔 — house
  { date: '2025-10-10', district: '大埔', building: '大埔獨立屋', categories: ['house'], unitType: '4房2廁', area: 2400, monthlyRent: 38000 },
  { date: '2025-08-04', district: '大埔', building: '大埔獨立屋', categories: ['house'], unitType: '3房2廁', area: 1800, monthlyRent: 28000 },
  { date: '2025-05-29', district: '大埔', building: '汀角路村屋', categories: ['house'], unitType: '3房2廁', area: 1750, monthlyRent: 26000 },
  { date: '2025-02-16', district: '大埔', building: '汀角路村屋', categories: ['house'], unitType: '4房3廁', area: 2200, monthlyRent: 34000 },
  { date: '2024-12-03', district: '大埔', building: '大埔獨立屋', categories: ['house'], unitType: '3房2廁', area: 1900, monthlyRent: 30000 },
  { date: '2024-09-17', district: '大埔', building: '汀角路村屋', categories: ['house'], unitType: '2房1廁', area: 1200, monthlyRent: 20000 },
];
